question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
{"text": "The Tiananmen Square protests of 1989 were held in Hong Kong.","answer": "False"},
{"text": "In 2016, the United Kingdom voted to stay in the EU.","answer": "False"},
{"text": "In Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing the main story.","answer": "False"},
{"text": "Denmark has a monarch.","answer": "True"},
{"text": "There are no deserts in Europe.","answer": "True"},
{"text": "Rabbits are rodents.","answer": "False"},
{"text": "The song &quot;Stronger Than You&quot; is a single by Estelle, who played Garnet in Steven Universe.","answer": "True"},
{"text": "Adolf Hitler was tried at the Nuremberg trials.","answer": "False"},
{"text": "Kublai Khan is the grandchild of Genghis Khan?","answer": "True"},
{"text": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.","answer": "True"}
]